### ISSUE TITLE
Crash nil pointer during storage accounts scan

### ISSUE THREAD

**Issue by pamontag** [cmendible/azqr#29] opened 2023-02-08 15:48 UTC
## Expected Behavior

During Storage Account scan inside a resource group, script crashes

2023/02/08 16:39:15 Analyzing SQL in Resource Group RG_CONTAINER_REGISTRY
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xed53ff]

goroutine 290 [running]:
github.com/cmendible/azqr/internal/scanners.(*StorageScanner).Scan(0xc000388840, {0xc000036180, 0x15})
        D:/a/azqr/azqr/internal/scanners/st.go:50 +0x19f
main.reviewRunner.func1(0xc0001331c0, {0xc000036180, 0x15})
        D:/a/azqr/azqr/cmd/azqr/main.go:195 +0x102
created by main.reviewRunner
        D:/a/azqr/azqr/cmd/azqr/main.go:189 +0x73

![image](https://user-images.githubusercontent.com/19266001/217578527-2dfcf104-fbdf-4e48-8d0a-271491db8f61.png)

## Steps to Reproduce the Problem

Crash happens during scan of storage accounts (presumed by st.go error)
Version used: latest release .\azqr-windows-latest-amd64.exe
azqr version: 0.7.3
No verbose logs can be shared, so is not possible to know deeply the root cause of the issue

**Comment by cmendible** [comment] 2023-02-08 16:26
Duplicate of #28 

Can you please check the build I posted there?

**Closed by cmendible** 2023-02-08 16:26 UTC
